{% set name = "PyWinBox" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kalmat/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5ac8f4cf46d423740e0afd72618b6f5a4a146f4480bc0863480e004b8ad06fff

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - pywin32 >=302  # [win]
    - python-xlib >=0.21  # [linux]
    - ewmhlib >=0.1  # [linux]
    - pyobjc-framework-cocoa >=8.1  # [osx]
    - typing_extensions >=4.4.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - "DISPLAY=localhost:1.0 XDG_SESSION_TYPE=x11 xvfb-run -a python -c 'import pywinbox'"  # [linux]
  imports:
    - pywinbox  # [not linux] pywinbox fails on import as no display is available

about:
  home: https://github.com/Kalmat/PyWinBox
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Cross-Platform and multi-monitor toolkit to handle rectangular areas and windows box'
  dev_url: https://github.com/Kalmat/PyWinBox

extra:
  recipe-maintainers:
    - '0xbe7a'
